"""Load proxy specs, run the enabled ones and follow hot-plug.

Spec directories, later ones override earlier ones by spec id:

- built-in: ``oversteer/proxy/profiles/*.json``
- system:   ``/etc/oversteer/proxies/*.json`` (what the daemon runs)
- user:     ``~/.config/oversteer/proxies/*.json`` (edited by the GUI)

The daemon (``oversteer --proxy-daemon``) runs as root so the real devices
can be made root-only (see :func:`hide_rules`) while the virtual devices it
creates get the normal joystick permissions.
"""

import glob
import json
import logging
import os
import re
import tempfile
import threading
import time

from .device import ProxyDevice
from .spec import ProxySpec, SpecError

BUILTIN_DIR = os.path.join(os.path.dirname(__file__), 'profiles')
SYSTEM_DIR = '/etc/oversteer/proxies'
STATUS_FILE = '/run/oversteer/proxies.json'
STATUS_HEARTBEAT = 60          # the daemon rewrites its status at least this often (seconds)
STATUS_STALE = 3 * STATUS_HEARTBEAT


def in_flatpak():
    return os.path.exists('/.flatpak-info')


def system_dir_readable():
    """Where to read the installed system specs from. Flatpak reserves /etc,
    so inside the sandbox the host's /etc is at /run/host/etc (host-etc)."""
    if in_flatpak():
        return os.path.join('/run/host', SYSTEM_DIR.lstrip('/'))
    return SYSTEM_DIR
# Two files: the uaccess tag must go before 73-seat-late.rules applies the
# ACL, and the mode/group must come after every other rule that grants
# access (Oversteer's own 99-* wheel rules, distro joystick rules).
HIDE_TAG_RULES_FILE = '/etc/udev/rules.d/71-oversteer-proxy-hide.rules'
HIDE_RULES_FILE = '/etc/udev/rules.d/99-zz-oversteer-proxy-hide.rules'


def user_dir():
    from xdg.BaseDirectory import save_config_path
    return os.path.join(save_config_path('oversteer'), 'proxies')


def load_specs(dirs):
    """Load specs from the given directories; later directories override
    earlier ones. Returns (specs by id, errors as [(path, message)])."""
    specs = {}
    errors = []
    for index, directory in enumerate(dirs):
        if not directory or not os.path.isdir(directory):
            continue
        for path in sorted(glob.glob(os.path.join(directory, '*.json'))):
            try:
                spec = ProxySpec.load(path, builtin=(directory == BUILTIN_DIR))
            except SpecError as e:
                errors.append((path, str(e)))
                logging.warning("proxy spec %s: %s", path, e)
                continue
            specs[spec.id] = spec
    return specs, errors


def hidden_sources(specs):
    """(vendor, product, label) for every hidden source of an enabled spec."""
    seen = {}
    for spec in sorted(specs.values(), key=lambda s: s.id):
        if not spec.enabled:
            continue
        for source in spec.sources.values():
            if not source.hide or source.vendor is None or source.product is None:
                continue
            seen.setdefault((source.vendor, source.product), '{} ({})'.format(spec.name, source.key))
    return [(v, p, label) for (v, p), label in seen.items()]


def hide_rules(specs, assignment='MODE="0600", GROUP="root"'):
    """udev rules making every hidden source root-only, so games can't open
    the real device and only see the proxy. Returns the rules file text.
    Labels are reduced to printable ASCII: anything else could smuggle a
    rule into a file udev runs as root."""
    lines = [
        "# Generated by Oversteer: real devices behind enabled proxies are hidden",
        "# from games; the proxy daemon (root) re-presents them as virtual devices.",
        "",
    ]
    for vendor, product, label in hidden_sources(specs):
        lines.append('# ' + re.sub(r'[^\x20-\x7e]', '?', label)[:120])
        for subsystem, kernel in (('input', 'KERNEL=="event*|js*", '), ('hidraw', '')):
            lines.append('SUBSYSTEM=="{}", {}ATTRS{{idVendor}}=="{:04x}", ATTRS{{idProduct}}=="{:04x}", {}'
                         .format(subsystem, kernel, vendor & 0xffff, product & 0xffff, assignment))
    lines.append("")
    return "\n".join(lines)


class ProxyManager:

    def __init__(self, dirs=None, status_file=None):
        self.dirs = dirs if dirs is not None else [BUILTIN_DIR, system_dir_readable(), user_dir()]
        self.status_file = status_file
        self.specs = {}
        self.errors = []
        self.proxies = {}
        self.observer = None
        self._lock = threading.Lock()
        self._status_lock = threading.Lock()

    def load(self):
        self.specs, self.errors = load_specs(self.dirs)
        return self.specs

    def enabled_specs(self):
        return [s for s in self.specs.values() if s.enabled]

    def start(self, only=None):
        """Start the enabled proxies (or just the ids in `only`)."""
        if not self.specs:
            self.load()
        if only:
            wanted = [s for s in self.specs.values() if s.id in only]
        else:
            wanted = self.enabled_specs()
        # The wheel must enumerate before its companions (games pick the first
        # device for force feedback): specs whose id others are derived from
        # go first, and each start waits for the previous device to exist.
        wanted.sort(key=lambda s: (any(o.id.startswith(s.id + '-') for o in wanted) is False, s.id))
        for spec in wanted:
            proxy = self.start_proxy(spec)
            deadline = time.monotonic() + 3.0
            while proxy.devnode is None and proxy.is_running() and time.monotonic() < deadline:
                time.sleep(0.05)
        self._start_monitor()
        self.write_status()

    def start_proxy(self, spec):
        with self._lock:
            if spec.id in self.proxies:
                return self.proxies[spec.id]
            proxy = ProxyDevice(spec, on_change=self._on_change)
            self.proxies[spec.id] = proxy
        proxy.start()
        return proxy

    def stop_proxy(self, spec_id):
        with self._lock:
            proxy = self.proxies.pop(spec_id, None)
        if proxy is not None:
            proxy.stop()
        self.write_status()

    def stop(self):
        if self.observer is not None:
            try:
                self.observer.stop()
            except Exception:
                pass
            self.observer = None
        with self._lock:
            proxies = list(self.proxies.values())
            self.proxies.clear()
        for proxy in proxies:
            proxy.stop()
        self.write_status()

    def _start_monitor(self):
        try:
            import pyudev
        except ImportError:
            logging.warning("pyudev not available: proxies rescan on a timer only")
            return
        context = pyudev.Context()
        monitor = pyudev.Monitor.from_netlink(context)
        monitor.filter_by('input')

        def on_event(action, device):
            if action == 'add' and device.device_node and 'event' in (device.get('DEVNAME') or ''):
                with self._lock:
                    proxies = list(self.proxies.values())
                for proxy in proxies:
                    if proxy.missing_sources():
                        proxy.poke()
        self.observer = pyudev.MonitorObserver(monitor, on_event)
        self.observer.daemon = True
        self.observer.start()

    def _on_change(self, proxy):
        self.write_status()

    def status(self):
        with self._lock:
            proxies = list(self.proxies.values())
        return {
            'pid': os.getpid(),
            'time': time.time(),
            'proxies': [p.status() for p in proxies],
            'errors': [{'path': p, 'error': e} for p, e in self.errors],
        }

    def write_status(self):
        if not self.status_file:
            return
        with self._status_lock:
            try:
                directory = os.path.dirname(self.status_file)
                os.makedirs(directory, exist_ok=True)
                fd, tmp = tempfile.mkstemp(prefix='.proxies.', dir=directory)
                with os.fdopen(fd, 'w') as f:
                    json.dump(self.status(), f, indent=1)
                os.chmod(tmp, 0o644)
                os.replace(tmp, self.status_file)
            except OSError as e:
                logging.debug("proxy status file: %s", e)

    @staticmethod
    def read_status(status_file=STATUS_FILE):
        """Status written by a running daemon, or None if there is none or
        the daemon that wrote it is gone."""
        try:
            with open(status_file) as f:
                status = json.load(f)
        except (OSError, ValueError):
            return None
        # Liveness: the daemon's pid on the host (not visible from a Flatpak
        # sandbox, so also a heartbeat the daemon refreshes).
        pid = status.get('pid')
        if pid and not in_flatpak() and not os.path.exists('/proc/{}'.format(pid)):
            return None
        written = status.get('time')
        if written and time.time() - written > STATUS_STALE:
            return None
        return status

    def describe(self):
        with self._lock:
            proxies = list(self.proxies.values())
        if not proxies:
            return "no proxies running"
        return "\n\n".join(p.describe() for p in proxies)
