"""Load proxy specs, run the enabled ones and follow hot-plug.

Spec directories, later ones override earlier ones by spec id:

- built-in: ``oversteer/proxy/profiles/*.json``
- system:   ``/etc/oversteer/proxies/*.json`` (what the daemon runs)
- user:     ``~/.config/oversteer/proxies/*.json`` (edited by the GUI)

The daemon (``oversteer --proxy-daemon``) runs as root so the real devices
can be made root-only (see :func:`hide_rules`) while the virtual devices it
creates get the normal joystick permissions.
"""

import glob
import json
import logging
import os
import threading

from .device import ProxyDevice
from .spec import ProxySpec, SpecError

BUILTIN_DIR = os.path.join(os.path.dirname(__file__), 'profiles')
SYSTEM_DIR = '/etc/oversteer/proxies'
STATUS_FILE = '/run/oversteer/proxies.json'
HIDE_RULES_FILE = '/etc/udev/rules.d/90-oversteer-proxy-hide.rules'


def user_dir():
    from xdg.BaseDirectory import save_config_path
    return os.path.join(save_config_path('oversteer'), 'proxies')


def load_specs(dirs):
    """Load specs from the given directories; later directories override
    earlier ones. Returns (specs by id, errors as [(path, message)])."""
    specs = {}
    errors = []
    for index, directory in enumerate(dirs):
        if not directory or not os.path.isdir(directory):
            continue
        for path in sorted(glob.glob(os.path.join(directory, '*.json'))):
            try:
                spec = ProxySpec.load(path, builtin=(directory == BUILTIN_DIR))
            except SpecError as e:
                errors.append((path, str(e)))
                logging.warning("proxy spec %s: %s", path, e)
                continue
            specs[spec.id] = spec
    return specs, errors


def hide_rules(specs):
    """udev rules making every hidden source root-only, so games can't open
    the real device and only see the proxy. Returns the rules file text."""
    lines = [
        "# Generated by Oversteer: real devices behind enabled proxies are hidden",
        "# from games; the proxy daemon (root) re-presents them as virtual devices.",
        "",
    ]
    seen = set()
    for spec in sorted(specs.values(), key=lambda s: s.id):
        if not spec.enabled:
            continue
        for source in spec.sources.values():
            if not source.hide or source.vendor is None or source.product is None:
                continue
            key = (source.vendor, source.product)
            if key in seen:
                continue
            seen.add(key)
            lines.append('# {} ({})'.format(spec.name, source.key))
            lines.append('SUBSYSTEM=="input", KERNEL=="event*|js*", ATTRS{{idVendor}}=="{:04x}", '
                         'ATTRS{{idProduct}}=="{:04x}", MODE="0600", GROUP="root", TAG-="uaccess"'
                         .format(source.vendor, source.product))
    lines.append("")
    return "\n".join(lines)


class ProxyManager:

    def __init__(self, dirs=None, status_file=None):
        self.dirs = dirs if dirs is not None else [BUILTIN_DIR, SYSTEM_DIR, user_dir()]
        self.status_file = status_file
        self.specs = {}
        self.errors = []
        self.proxies = {}
        self.observer = None
        self._lock = threading.Lock()

    def load(self):
        self.specs, self.errors = load_specs(self.dirs)
        return self.specs

    def enabled_specs(self):
        return [s for s in self.specs.values() if s.enabled]

    def start(self, only=None):
        """Start the enabled proxies (or just the ids in `only`)."""
        if not self.specs:
            self.load()
        if only:
            wanted = [s for s in self.specs.values() if s.id in only]
        else:
            wanted = self.enabled_specs()
        for spec in wanted:
            self.start_proxy(spec)
        self._start_monitor()
        self.write_status()

    def start_proxy(self, spec):
        with self._lock:
            if spec.id in self.proxies:
                return self.proxies[spec.id]
            proxy = ProxyDevice(spec, on_change=self._on_change)
            self.proxies[spec.id] = proxy
        proxy.start()
        return proxy

    def stop_proxy(self, spec_id):
        with self._lock:
            proxy = self.proxies.pop(spec_id, None)
        if proxy is not None:
            proxy.stop()
        self.write_status()

    def stop(self):
        if self.observer is not None:
            try:
                self.observer.stop()
            except Exception:
                pass
            self.observer = None
        with self._lock:
            proxies = list(self.proxies.values())
            self.proxies.clear()
        for proxy in proxies:
            proxy.stop()
        self.write_status()

    def _start_monitor(self):
        try:
            import pyudev
        except ImportError:
            logging.warning("pyudev not available: proxies rescan on a timer only")
            return
        context = pyudev.Context()
        monitor = pyudev.Monitor.from_netlink(context)
        monitor.filter_by('input')

        def on_event(action, device):
            if action == 'add' and device.device_node and 'event' in (device.get('DEVNAME') or ''):
                with self._lock:
                    proxies = list(self.proxies.values())
                for proxy in proxies:
                    if proxy.missing_sources():
                        proxy.poke()
        self.observer = pyudev.MonitorObserver(monitor, on_event)
        self.observer.daemon = True
        self.observer.start()

    def _on_change(self, proxy):
        self.write_status()

    def status(self):
        with self._lock:
            proxies = list(self.proxies.values())
        return {
            'proxies': [p.status() for p in proxies],
            'errors': [{'path': p, 'error': e} for p, e in self.errors],
        }

    def write_status(self):
        if not self.status_file:
            return
        try:
            os.makedirs(os.path.dirname(self.status_file), exist_ok=True)
            tmp = self.status_file + '.tmp'
            with open(tmp, 'w') as f:
                json.dump(self.status(), f, indent=1)
            os.replace(tmp, self.status_file)
        except OSError as e:
            logging.debug("proxy status file: %s", e)

    @staticmethod
    def read_status(status_file=STATUS_FILE):
        """Status written by a running daemon, or None."""
        try:
            with open(status_file) as f:
                return json.load(f)
        except (OSError, ValueError):
            return None

    def describe(self):
        with self._lock:
            proxies = list(self.proxies.values())
        if not proxies:
            return "no proxies running"
        return "\n\n".join(p.describe() for p in proxies)
